name: Publish HF Space Docker Image

on:
  release:
    types: [created] # 当有新的 release 被创建时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up QEMU # 可选：如果经常构建多架构镜像，可以加上这个步骤，能提高构建速度，但目前docker/setup-buildx-action@v2已经包含了大部分需要的功能，可以先不加。
      #   uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          # 使用 buildx bake 可以更好地指定多个 tag，但为了简化，这里直接在 tags 里生成
          driver-opts: |
             image: moby/buildkit:v0.11.6 # 推荐指定buildkit版本，避免潜在问题

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # 推荐使用最新版本 v5
        with:
          context: .  # 保持构建上下文为仓库根目录
          platforms: linux/amd64,linux/arm64
          push: true
          # 同时打上 latest 和 release tag (例如：your_docker_username/hfspace:latest 和 your_docker_username/hfspace:v1.0.0)
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hfspace:latest
            ${{ secrets.DOCKER_USERNAME }}/hfspace:${{ github.event.release.tag_name }}
