name: Build and Push Docker Image to GHCR

on:
  workflow_dispatch: # 添加手动触发事件

jobs:
  build:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 环境下运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 检出代码

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # 设置 Docker Buildx，用于更高效地构建镜像

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3 # 登录到 ghcr.io
        with:
          registry: ghcr.io # 指定注册表为 ghcr.io
          username: ${{ github.actor }} # 使用触发 workflow 的用户或 bot 名称作为用户名
          password: ${{ secrets.GITHUB_TOKEN }} # 使用内置的 GITHUB_TOKEN 作为密码

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # 构建并推送 Docker 镜像
        with:
          context: . # Dockerfile 的上下文路径，这里是仓库根目录
          file: ./Dockerfile # Dockerfile 的路径
          push: true # 设置为 true 表示构建后立即推送
          tags: | # 定义镜像标签，使用更精确的变量
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}